#2) Escreva um programa que faça a busca de um valor 
#em uma lista de inteiros e informe a posição
#do valor na lista. Otimize a busca de modo que não seja necessário 
#percorrer o restante da lista quando o valor for encontrado.

lista = [2,23,45,12,15,4,60]

for i in range(1):
     valor = int(input("Qual valor voce quer pesquisar: "))
     indice = lista.index(valor)
     if valor == indice: 
      break

print("O indice do valor digitado é :",indice)


# EXERCICO 1

previsao = [10, 23, 45, -12, -56]

total = 0 
contador = 0 

for precipitacao in previsao:     
      if precipitacao > 0:
         total += precipitacao
         contador += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
if contador == 0:
   print("SEM CHUVA")
else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
 media = total / contador
print("Total :", total)
print("Dias com chuva:", contador)
print("Média :", media)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        